server:
  port: 7081
spring:
  datasource:
    url: jdbc:mysql://139.9.92.208:3306/kkfileview?useSSL=false
    username: root
    password: asD484942
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 1909484942@qq.com # 登录qq邮箱的账号
    password: hpyvmbppfrzmeegi # 开启 IMAP/SMTP服务 获得的授权码
    default-encoding: UTF-8
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS